apiVersion: v1
kind: Service
metadata:
    name: "akseurope01demo-e528"
    labels:
        app: "akseurope01demo-e528"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akseurope01demo-e528"