on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n acraks01adrian -g acraks01adrianaf1f-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n acraks01adrian --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n acraks01adrian --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n acraks01adrian --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: acraks01adrian.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acraks01adrian.azurecr.io/akseurope01demo:${{ github.sha }}
        docker push acraks01adrian.azurecr.io/akseurope01demo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_akseurope01demo_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-europe01-demo8f62 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-europe01-demo8f62`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-europe01-demo8f62
        container-registry-url: acraks01adrian.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: akseurope01ddockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-europe01-demo8f62
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          acraks01adrian.azurecr.io/akseurope01demo:${{ github.sha }}
        imagepullsecrets: |
          akseurope01ddockerauth